// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CapturePage(arg1:string,arg2:string):Promise<string>;

export function DownloadFile(arg1:string):Promise<string>;

export function GetCaptureProgress():Promise<string>;

export function OpenDirectory(arg1:string):Promise<string>;

export function OpenUrl(arg1:string):Promise<string>;

export function SaveZipToDirectory(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function StopCapture():Promise<string>;
