// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CapturePage(arg1, arg2) {
  return window['go']['main']['App']['CapturePage'](arg1, arg2);
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function GetCaptureProgress() {
  return window['go']['main']['App']['GetCaptureProgress']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenUrl(arg1) {
  return window['go']['main']['App']['OpenUrl'](arg1);
}

export function SaveZipToDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveZipToDirectory'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}
